# Generated by Django 5.0.7 on 2024-08-29 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_tag_post_tags_post_thumbs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbs',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbsdown',
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbsup',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbsup',
            field=models.ManyToManyField(blank=True, default=None, related_name='thumbs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='postid', to='blog.post'),
        ),
    ]
