# Generated by Django 5.0.7 on 2024-08-29 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_thumbs_remove_post_thumbsdown_vote_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbsup',
            field=models.ManyToManyField(blank=True, default=None, related_name='thumbsup', to=settings.AUTH_USER_MODEL),
        ),
    ]
