# Generated by Django 5.0.7 on 2024-08-29 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_thumbsup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbsup',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbsups',
            field=models.ManyToManyField(blank=True, default=None, related_name='post_thumbsup', to=settings.AUTH_USER_MODEL),
        ),
    ]
