# Generated by Django 5.0.7 on 2024-08-29 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_thumbsup_post_thumbsups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbsdowns',
            field=models.ManyToManyField(blank=True, default=None, related_name='post_thumbsdown', to=settings.AUTH_USER_MODEL),
        ),
    ]
