# Generated by Django 5.0.7 on 2024-08-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_thumbsdowns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, related_name='tag', to='blog.tag'),
        ),
    ]
